export const sources = {
  AUTH: 'auth/local',
  EVENTS: 'events',
  CAMPAIGNS: 'campaigns',
  ADVERTISERS: 'advertisers',
  CREATIVITYGROUPS: 'creativity-groups',
  UPLOAD: 'upload',
  USERS: 'users',
  ROLES: 'users-permissions/roles',
  ROUTES_INFOS: 'routes-infos',
  PERMISSIONS: 'custom-permissions',
  ROLE_PERMISSION: 'custom-permission',
  CREATIVITY: 'creativity',
  SALES: 'ad-sale-platforms',
  SALESPOST: 'ad-sale-platform/create-sale-platform',
  SCREENS: 'screens',
  RESOLUTIONS: 'resolutions',
  SCREENPLATFORMSALE: 'sales-platform-screens',
  PLATFORMPLAYER: 'ad-reproduction-platforms',
  PLATFORM: 'platforms',
  PLAYER: 'players',
  SCREENPLAYER: 'screen-players',
  ORGANIZATION: 'organizations',
  LOGS: 'user-action-logs',
  CONFIGURATION: 'global-configuration',
};
